version: '3'

services:

    cloudflareddns:
        container_name: cloudflareddns
        image: taoofshawn/cloudflareddns
        environment:
            - APITOKEN=<token from cloudflare>
            - POLLTIME=360
            - TZ=America/New_York
            - NAMELIST=www.example.com,
                example.com,
                www.example2.com,
                example2.com


